In [1]:
import pandas as pd

In [5]:
df = pd.read_excel("Crimes_-_2001_to_Present_20250527 (1).xlsx")

In [7]:
df.describe()

,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude
count,50267.000000,50267.000000,50267.000000,50266.000000,5.023600e+04,5.023600e+04,50267.0,50236.000000,50236.000000
mean,1144.283844,11.213122,23.068435,36.584073,1.165526e+06,1.886913e+06,2025.0,41.845267,-87.668071
std,705.941046,7.054900,13.842874,21.523639,1.643659e+04,3.143801e+04,0.0,0.086456,0.059849
min,111.000000,1.000000,1.000000,1.000000,1.093568e+06,1.813909e+06,2025.0,41.644608,-87.931147
25%,532.000000,5.000000,10.000000,23.000000,1.153977e+06,1.860051e+06,2025.0,41.771431,-87.710013
50%,1031.000000,10.000000,23.000000,32.000000,1.167456e+06,1.893243e+06,2025.0,41.862866,-87.660694
75%,1724.000000,17.000000,34.000000,53.000000,1.176818e+06,1.909530e+06,2025.0,41.907467,-87.626539
max,2535.000000,31.000000,50.000000,77.000000,1.205119e+06,1.951517e+06,2025.0,42.022559,-87.524532

In [9]:
df.columns

Index(['Case Number', 'Date', 'Block', 'IUCR', 'Primary Type', 'Description',
       'Location Description', 'Arrest', 'Domestic', 'Beat', 'District',
       'Ward', 'Community Area', 'FBI Code', 'X Coordinate', 'Y Coordinate',
       'Year', 'Updated On', 'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [10]:
df.head()

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,JJ260129,05/18/2025 12:00:00 AM,034XX N CLARK ST,0460,BATTERY,SIMPLE,BAR OR TAVERN,False,False,1924,...,44,6.0,08B,1168850.0,1923293.0,2025,05/25/2025 03:42:20 PM,41.945040,-87.654775,"(41.945039683, -87.654774622)"
1,JJ260746,05/18/2025 12:00:00 AM,022XX N LINCOLN AVE,0870,THEFT,POCKET-PICKING,BAR OR TAVERN,False,False,1812,...,43,7.0,06,1171478.0,1915284.0,2025,05/25/2025 03:42:20 PM,41.923005,-87.645351,"(41.923005158, -87.645351431)"
2,JJ259628,05/18/2025 12:00:00 AM,088XX S BURLEY AVE,0820,THEFT,$500 AND UNDER,RESIDENCE,False,True,424,...,10,46.0,06,1199205.0,1846953.0,2025,05/25/2025 03:42:20 PM,41.734847,-87.545777,"(41.734847232, -87.545777045)"
3,JJ259414,05/18/2025 12:00:00 AM,067XX S EVANS AVE,0497,BATTERY,AGGRAVATED DOMESTIC BATTERY - OTHER DANGEROUS ...,STREET,False,True,321,...,6,42.0,04B,1182379.0,1860397.0,2025,05/25/2025 03:42:20 PM,41.772145,-87.607004,"(41.77214496, -87.60700369)"
4,JJ259766,05/18/2025 12:00:00 AM,006XX N FRANKLIN ST,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,1831,...,42,8.0,14,1174214.0,1904528.0,2025,05/25/2025 03:42:20 PM,41.893429,-87.635620,"(41.893429499, -87.635619998)"

<bound method NDFrame.describe of       Case Number                    Date                  Block  IUCR  \
0        JJ260129  05/18/2025 12:00:00 AM       034XX N CLARK ST  0460
1        JJ260746  05/18/2025 12:00:00 AM    022XX N LINCOLN AVE  0870
2        JJ259628  05/18/2025 12:00:00 AM     088XX S BURLEY AVE  0820
3        JJ259414  05/18/2025 12:00:00 AM      067XX S EVANS AVE  0497
4        JJ259766  05/18/2025 12:00:00 AM    006XX N FRANKLIN ST  1310
...           ...                     ...                    ...   ...
50262    JJ163966  02/27/2025 10:46:00 AM  050XX S Hermitage ave  1130
50263    JJ163639  02/27/2025 10:45:00 AM        003XX W 64TH ST  0460
50264    JJ163666  02/27/2025 10:45:00 AM        023XX W 21ST ST  0486
50265    JJ163621  02/27/2025 10:44:00 AM   007XX N FAIRBANKS CT  1345
50266    JJ163645  02/27/2025 10:36:00 AM     080XX S HALSTED ST  051A

             Primary Type                                        Description  \
0                 BATTERY                                             SIMPLE
1                   THEFT                                     POCKET-PICKING
2                   THEFT                                     $500 AND UNDER
3                 BATTERY  AGGRAVATED DOMESTIC BATTERY - OTHER DANGEROUS ...
4         CRIMINAL DAMAGE                                        TO PROPERTY
...                   ...                                                ...
50262  DECEPTIVE PRACTICE                           FRAUD OR CONFIDENCE GAME
50263             BATTERY                                             SIMPLE
50264             BATTERY                            DOMESTIC BATTERY SIMPLE
50265     CRIMINAL DAMAGE                        TO CITY OF CHICAGO PROPERTY
50266             ASSAULT                               AGGRAVATED - HANDGUN

               Location Description  Arrest  Domestic  Beat  ...  Ward  \
0                     BAR OR TAVERN   False     False  1924  ...    44
1                     BAR OR TAVERN   False     False  1812  ...    43
2                         RESIDENCE   False      True   424  ...    10
3                            STREET   False      True   321  ...     6
4                         APARTMENT   False     False  1831  ...    42
...                             ...     ...       ...   ...  ...   ...
50262  COMMERCIAL / BUSINESS OFFICE   False     False   931  ...    20
50263                     APARTMENT   False     False   722  ...    20
50264                     APARTMENT   False      True  1234  ...    25
50265                        STREET   False     False  1834  ...     2
50266            SMALL RETAIL STORE   False     False   621  ...    17

       Community Area  FBI Code X Coordinate  Y Coordinate  Year  \
0                 6.0       08B    1168850.0     1923293.0  2025
1                 7.0        06    1171478.0     1915284.0  2025
2                46.0        06    1199205.0     1846953.0  2025
3                42.0       04B    1182379.0     1860397.0  2025
4                 8.0        14    1174214.0     1904528.0  2025
...               ...       ...          ...           ...   ...
50262            61.0        11    1165529.0     1871337.0  2025
50263            68.0       08B    1175335.0     1862515.0  2025
50264            31.0       08B    1161109.0     1890015.0  2025
50265             8.0        14    1178370.0     1905271.0  2025
50266            71.0       04A    1172366.0     1851547.0  2025

                   Updated On   Latitude  Longitude  \
0      05/25/2025 03:42:20 PM  41.945040 -87.654775
1      05/25/2025 03:42:20 PM  41.923005 -87.645351
2      05/25/2025 03:42:20 PM  41.734847 -87.545777
3      05/25/2025 03:42:20 PM  41.772145 -87.607004
4      05/25/2025 03:42:20 PM  41.893429 -87.635620
...                       ...        ...        ...
50262  05/17/2025 03:40:52 PM  41.802540 -87.668461
50263  05/17/2025 03:40:52 PM  41.778117 -87.632761
50264  05/17/2025 03:40:52 PM  41.853887 -87.684153
50265  05/17/2025 03:40:52 PM  41.895375 -87.620334
50266  05/17/2025 03:40:52 PM  41.748086 -87.643968

                            Location
0      (41.945039683, -87.654774622)
1      (41.923005158, -87.645351431)
2      (41.734847232, -87.545777045)
3        (41.77214496, -87.60700369)
4      (41.893429499, -87.635619998)
...                              ...
50262  (41.802539586, -87.668460521)
50263   (41.77811733, -87.632761451)
50264  (41.853886831, -87.684153011)
50265  (41.895374574, -87.620333997)
50266   (41.74808565, -87.643968122)

[50267 rows x 21 columns]>

In [25]:
import os
import json
from pneuma import Pneuma

In [13]:
import torch

In [24]:
torch.cuda.current_device()

0

In [21]:
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [ ]:
pneuma = Pneuma(
    out_path="my_pneuma_output",
    use_local_model=True,  # This enables HF models
    llm_path="Qwen/Qwen2.5-7B-Instruct",  # HF model for text generation
    embed_path="BAAI/bge-base-en-v1.5",   # HF model for embeddings
    hf_token="your_token_here",  # Optional: for gated models
    max_llm_batch_size=2,  # Adjust based on your GPU memory
)